MERGE INTO tb_rank AS TARGET
USING (VALUES('125', 135)) AS Source(id, score)
ON TARGET.id = Source.id
WHEN MATCHED THEN
UPDATE SET TARGET.score = 135
WHEN NOT MATCHED BY TARGET THEN
INSERT(id, score) VALUES('125', 135);
